substitutions:
  '_BASE_IMAGE': 'cos-dev-105-17234-0-0'
  '_OUTPUT_IMAGE_PREFIX': 'confidential-space'
  '_OUTPUT_IMAGE_SUFFIX': ''

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  env:
  - 'BASE_IMAGE=$_BASE_IMAGE'
  - 'OUTPUT_IMAGE_PREFIX=$_OUTPUT_IMAGE_PREFIX'
  - 'OUTPUT_IMAGE_SUFFIX=$_OUTPUT_IMAGE_SUFFIX'
  - 'PROJECT_ID=$PROJECT_ID'
  script: |
    #!/usr/bin/env bash

    # if BASE_IMAGE is not specified, use the latest COS dev image
    base_image=${BASE_IMAGE}
    if [ -z ${base_image}]
    then
      echo "getting the latest COS image"
      base_image=$(gcloud compute images describe-from-family cos-dev --project cos-cloud | grep name | cut -d ' ' -f 2)
    fi

    debug_image_name=${OUTPUT_IMAGE_PREFIX}-debug-${OUTPUT_IMAGE_SUFFIX}
    hardened_image_name=${OUTPUT_IMAGE_PREFIX}-hardened-${OUTPUT_IMAGE_SUFFIX}

    echo "building the debug image with the base image: ${base_image}"
    gcloud builds submit --config=launcher/image/cloudbuild.yaml \
      --substitutions _BASE_IMAGE=${base_image},_OUTPUT_IMAGE_NAME=${debug_image_name},_IMAGE_ENV=debug &

    echo "building the hardened image with the base image: ${base_image}"
    gcloud builds submit --config=launcher/image/cloudbuild.yaml \
      --substitutions _BASE_IMAGE=${base_image},_OUTPUT_IMAGE_NAME=${hardened_image_name},_IMAGE_ENV=hardened &

    echo "waiting for images to be built..."
    wait

    echo "running hardened image tests on ${hardened_image_name}"
    cd launcher/image/test
    gcloud builds submit --config=test_hardened_cloudbuild.yaml \
      --substitutions _IMAGE_NAME=${hardened_image_name},_IMAGE_PROJECT=${PROJECT_ID}
